package org.wso2.micro.gateway.enforcer.constants;

public class ConfigDefaultValues {
    public static final String DEFAULT_TM_BINARY_AGENT_PROTOCOL_VERSIONS = "TLSv1,TLSv1.1,TLSv1.2";
    public static final String DEFAULT_TM_BINARY_AGENT_CIPHERS = "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, "
            + "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, "
            + "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, "
            + "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA, "
            + "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDH_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_128_CBC_SHA, "
            + " TLS_DHE_DSS_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, "
            + "TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, "
            + "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 , "
            + "TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,SSL_RSA_WITH_3DES_EDE_CBC_SHA, "
            + "TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA,SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, "
            + "SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA,TLS_EMPTY_RENEGOTIATION_INFO_SCSV";
    public static final int DEFAULT_TM_AGENT_QUEUE_SIZE = 32768;
    public static final int DEFAULT_TM_AGENT_BATCH_SIZE = 200;
    public static final int DEFAULT_TM_AGENT_THREAD_POOL_CORE_SIZE = 1;
    public static final int DEFAULT_TM_AGENT_SOCKET_TIMEOUT_MS = 30000;
    public static final int DEFAULT_TM_AGENT_THREAD_POOL_MAXIMUM_SIZE = 1;
    public static final int DEFAULT_TM_AGENT_THREAD_POOL_KEEP_ALIVE_TIME = 20;
    public static final int DEFAULT_TM_AGENT_RECONNECTION_INTERVAL = 30;
    public static final int DEFAULT_TM_AGENT_MAX_TRANSPORT_POOL_SIZE = 250;
    public static final int DEFAULT_TM_AGENT_MAX_IDLE_CONNECTIONS = 250;
    public static final int DEFAULT_TM_AGENT_EVICTION_TIME_PERIOD = 5500;
    public static final int DEFAULT_TM_AGENT_MIN_IDLE_TIME_IN_POOL = 5000;
    public static final int DEFAULT_TM_AGENT_SECURE_MAX_TRANSPORT_POOL_SIZE = 250;
    public static final int DEFAULT_TM_AGENT_SECURE_MAX_IDLE_CONNECTIONS = 250;
    public static final int DEFAULT_TM_AGENT_SECURE_EVICTION_TIME_PERIOD = 5500;
    public static final int DEFAULT_TM_AGENT_SECURE_MIN_IDLE_TIME_IN_POOL = 5000;
}
