[project]
org-name= "wso2"
version= "0.1.0"

[platform]
target = "java8"

    [[platform.libraries]]
    path = "${MICROGW_HOME}/lib/gateway/platform/org.wso2.micro.gateway.core-3.0.2-SNAPSHOT.jar"

[dependencies]
"wso2/jms" = "0.6.2"
