// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Analytics.proto

package org.wso2.micro.gateway.filter.core.grpc.server.analytics;

public interface AnalyticsStreamMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnalyticsStreamMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messageStreamName = 1;</code>
   * @return The messageStreamName.
   */
  java.lang.String getMessageStreamName();
  /**
   * <code>string messageStreamName = 1;</code>
   * @return The bytes for messageStreamName.
   */
  com.google.protobuf.ByteString
      getMessageStreamNameBytes();

  /**
   * <code>string meta_clientType = 2;</code>
   * @return The metaClientType.
   */
  java.lang.String getMetaClientType();
  /**
   * <code>string meta_clientType = 2;</code>
   * @return The bytes for metaClientType.
   */
  com.google.protobuf.ByteString
      getMetaClientTypeBytes();

  /**
   * <code>string applicationConsumerKey = 3;</code>
   * @return The applicationConsumerKey.
   */
  java.lang.String getApplicationConsumerKey();
  /**
   * <code>string applicationConsumerKey = 3;</code>
   * @return The bytes for applicationConsumerKey.
   */
  com.google.protobuf.ByteString
      getApplicationConsumerKeyBytes();

  /**
   * <code>string applicationName = 4;</code>
   * @return The applicationName.
   */
  java.lang.String getApplicationName();
  /**
   * <code>string applicationName = 4;</code>
   * @return The bytes for applicationName.
   */
  com.google.protobuf.ByteString
      getApplicationNameBytes();

  /**
   * <code>string applicationId = 5;</code>
   * @return The applicationId.
   */
  java.lang.String getApplicationId();
  /**
   * <code>string applicationId = 5;</code>
   * @return The bytes for applicationId.
   */
  com.google.protobuf.ByteString
      getApplicationIdBytes();

  /**
   * <code>string applicationOwner = 6;</code>
   * @return The applicationOwner.
   */
  java.lang.String getApplicationOwner();
  /**
   * <code>string applicationOwner = 6;</code>
   * @return The bytes for applicationOwner.
   */
  com.google.protobuf.ByteString
      getApplicationOwnerBytes();

  /**
   * <code>string apiContext = 7;</code>
   * @return The apiContext.
   */
  java.lang.String getApiContext();
  /**
   * <code>string apiContext = 7;</code>
   * @return The bytes for apiContext.
   */
  com.google.protobuf.ByteString
      getApiContextBytes();

  /**
   * <code>string apiName = 8;</code>
   * @return The apiName.
   */
  java.lang.String getApiName();
  /**
   * <code>string apiName = 8;</code>
   * @return The bytes for apiName.
   */
  com.google.protobuf.ByteString
      getApiNameBytes();

  /**
   * <code>string apiVersion = 9;</code>
   * @return The apiVersion.
   */
  java.lang.String getApiVersion();
  /**
   * <code>string apiVersion = 9;</code>
   * @return The bytes for apiVersion.
   */
  com.google.protobuf.ByteString
      getApiVersionBytes();

  /**
   * <code>string apiResourcePath = 10;</code>
   * @return The apiResourcePath.
   */
  java.lang.String getApiResourcePath();
  /**
   * <code>string apiResourcePath = 10;</code>
   * @return The bytes for apiResourcePath.
   */
  com.google.protobuf.ByteString
      getApiResourcePathBytes();

  /**
   * <code>string apiResourceTemplate = 11;</code>
   * @return The apiResourceTemplate.
   */
  java.lang.String getApiResourceTemplate();
  /**
   * <code>string apiResourceTemplate = 11;</code>
   * @return The bytes for apiResourceTemplate.
   */
  com.google.protobuf.ByteString
      getApiResourceTemplateBytes();

  /**
   * <code>string apiMethod = 12;</code>
   * @return The apiMethod.
   */
  java.lang.String getApiMethod();
  /**
   * <code>string apiMethod = 12;</code>
   * @return The bytes for apiMethod.
   */
  com.google.protobuf.ByteString
      getApiMethodBytes();

  /**
   * <code>string apiCreator = 13;</code>
   * @return The apiCreator.
   */
  java.lang.String getApiCreator();
  /**
   * <code>string apiCreator = 13;</code>
   * @return The bytes for apiCreator.
   */
  com.google.protobuf.ByteString
      getApiCreatorBytes();

  /**
   * <code>string apiCreatorTenantDomain = 14;</code>
   * @return The apiCreatorTenantDomain.
   */
  java.lang.String getApiCreatorTenantDomain();
  /**
   * <code>string apiCreatorTenantDomain = 14;</code>
   * @return The bytes for apiCreatorTenantDomain.
   */
  com.google.protobuf.ByteString
      getApiCreatorTenantDomainBytes();

  /**
   * <code>string apiTier = 15;</code>
   * @return The apiTier.
   */
  java.lang.String getApiTier();
  /**
   * <code>string apiTier = 15;</code>
   * @return The bytes for apiTier.
   */
  com.google.protobuf.ByteString
      getApiTierBytes();

  /**
   * <code>string apiHostname = 16;</code>
   * @return The apiHostname.
   */
  java.lang.String getApiHostname();
  /**
   * <code>string apiHostname = 16;</code>
   * @return The bytes for apiHostname.
   */
  com.google.protobuf.ByteString
      getApiHostnameBytes();

  /**
   * <code>string username = 17;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 17;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string userTenantDomain = 18;</code>
   * @return The userTenantDomain.
   */
  java.lang.String getUserTenantDomain();
  /**
   * <code>string userTenantDomain = 18;</code>
   * @return The bytes for userTenantDomain.
   */
  com.google.protobuf.ByteString
      getUserTenantDomainBytes();

  /**
   * <code>string userIp = 19;</code>
   * @return The userIp.
   */
  java.lang.String getUserIp();
  /**
   * <code>string userIp = 19;</code>
   * @return The bytes for userIp.
   */
  com.google.protobuf.ByteString
      getUserIpBytes();

  /**
   * <code>string userAgent = 20;</code>
   * @return The userAgent.
   */
  java.lang.String getUserAgent();
  /**
   * <code>string userAgent = 20;</code>
   * @return The bytes for userAgent.
   */
  com.google.protobuf.ByteString
      getUserAgentBytes();

  /**
   * <code>int64 requestTimestamp = 21;</code>
   * @return The requestTimestamp.
   */
  long getRequestTimestamp();

  /**
   * <code>bool throttledOut = 22;</code>
   * @return The throttledOut.
   */
  boolean getThrottledOut();

  /**
   * <code>int64 responseTime = 23;</code>
   * @return The responseTime.
   */
  long getResponseTime();

  /**
   * <code>int64 serviceTime = 24;</code>
   * @return The serviceTime.
   */
  long getServiceTime();

  /**
   * <code>int64 backendTime = 25;</code>
   * @return The backendTime.
   */
  long getBackendTime();

  /**
   * <code>bool responseCacheHit = 26;</code>
   * @return The responseCacheHit.
   */
  boolean getResponseCacheHit();

  /**
   * <code>int64 responseSize = 27;</code>
   * @return The responseSize.
   */
  long getResponseSize();

  /**
   * <code>string protocol = 28;</code>
   * @return The protocol.
   */
  java.lang.String getProtocol();
  /**
   * <code>string protocol = 28;</code>
   * @return The bytes for protocol.
   */
  com.google.protobuf.ByteString
      getProtocolBytes();

  /**
   * <code>int32 responseCode = 29;</code>
   * @return The responseCode.
   */
  int getResponseCode();

  /**
   * <code>string destination = 30;</code>
   * @return The destination.
   */
  java.lang.String getDestination();
  /**
   * <code>string destination = 30;</code>
   * @return The bytes for destination.
   */
  com.google.protobuf.ByteString
      getDestinationBytes();

  /**
   * <code>int64 securityLatency = 31;</code>
   * @return The securityLatency.
   */
  long getSecurityLatency();

  /**
   * <code>int64 throttlingLatency = 32;</code>
   * @return The throttlingLatency.
   */
  long getThrottlingLatency();

  /**
   * <code>int64 requestMedLat = 33;</code>
   * @return The requestMedLat.
   */
  long getRequestMedLat();

  /**
   * <code>int64 responseMedLat = 34;</code>
   * @return The responseMedLat.
   */
  long getResponseMedLat();

  /**
   * <code>int64 backendLatency = 35;</code>
   * @return The backendLatency.
   */
  long getBackendLatency();

  /**
   * <code>int64 otherLatency = 36;</code>
   * @return The otherLatency.
   */
  long getOtherLatency();

  /**
   * <code>string gatewayType = 37;</code>
   * @return The gatewayType.
   */
  java.lang.String getGatewayType();
  /**
   * <code>string gatewayType = 37;</code>
   * @return The bytes for gatewayType.
   */
  com.google.protobuf.ByteString
      getGatewayTypeBytes();

  /**
   * <code>string label = 38;</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 38;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>string subscriber = 39;</code>
   * @return The subscriber.
   */
  java.lang.String getSubscriber();
  /**
   * <code>string subscriber = 39;</code>
   * @return The bytes for subscriber.
   */
  com.google.protobuf.ByteString
      getSubscriberBytes();

  /**
   * <code>string throttledOutReason = 40;</code>
   * @return The throttledOutReason.
   */
  java.lang.String getThrottledOutReason();
  /**
   * <code>string throttledOutReason = 40;</code>
   * @return The bytes for throttledOutReason.
   */
  com.google.protobuf.ByteString
      getThrottledOutReasonBytes();

  /**
   * <code>int64 throttledOutTimestamp = 41;</code>
   * @return The throttledOutTimestamp.
   */
  long getThrottledOutTimestamp();

  /**
   * <code>string hostname = 42;</code>
   * @return The hostname.
   */
  java.lang.String getHostname();
  /**
   * <code>string hostname = 42;</code>
   * @return The bytes for hostname.
   */
  com.google.protobuf.ByteString
      getHostnameBytes();

  /**
   * <code>string errorCode = 43;</code>
   * @return The errorCode.
   */
  java.lang.String getErrorCode();
  /**
   * <code>string errorCode = 43;</code>
   * @return The bytes for errorCode.
   */
  com.google.protobuf.ByteString
      getErrorCodeBytes();

  /**
   * <code>string errorMessage = 44;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 44;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
