// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Analytics.proto

package org.wso2.micro.gateway.filter.core.grpc.server.analytics;

public final class Analytics {
  private Analytics() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnalyticsStreamMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnalyticsStreamMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Analytics.proto\032\033google/protobuf/empty" +
      ".proto\"\375\007\n\026AnalyticsStreamMessage\022\031\n\021mes" +
      "sageStreamName\030\001 \001(\t\022\027\n\017meta_clientType\030" +
      "\002 \001(\t\022\036\n\026applicationConsumerKey\030\003 \001(\t\022\027\n" +
      "\017applicationName\030\004 \001(\t\022\025\n\rapplicationId\030" +
      "\005 \001(\t\022\030\n\020applicationOwner\030\006 \001(\t\022\022\n\napiCo" +
      "ntext\030\007 \001(\t\022\017\n\007apiName\030\010 \001(\t\022\022\n\napiVersi" +
      "on\030\t \001(\t\022\027\n\017apiResourcePath\030\n \001(\t\022\033\n\023api" +
      "ResourceTemplate\030\013 \001(\t\022\021\n\tapiMethod\030\014 \001(" +
      "\t\022\022\n\napiCreator\030\r \001(\t\022\036\n\026apiCreatorTenan" +
      "tDomain\030\016 \001(\t\022\017\n\007apiTier\030\017 \001(\t\022\023\n\013apiHos" +
      "tname\030\020 \001(\t\022\020\n\010username\030\021 \001(\t\022\030\n\020userTen" +
      "antDomain\030\022 \001(\t\022\016\n\006userIp\030\023 \001(\t\022\021\n\tuserA" +
      "gent\030\024 \001(\t\022\030\n\020requestTimestamp\030\025 \001(\003\022\024\n\014" +
      "throttledOut\030\026 \001(\010\022\024\n\014responseTime\030\027 \001(\003" +
      "\022\023\n\013serviceTime\030\030 \001(\003\022\023\n\013backendTime\030\031 \001" +
      "(\003\022\030\n\020responseCacheHit\030\032 \001(\010\022\024\n\014response" +
      "Size\030\033 \001(\003\022\020\n\010protocol\030\034 \001(\t\022\024\n\014response" +
      "Code\030\035 \001(\005\022\023\n\013destination\030\036 \001(\t\022\027\n\017secur" +
      "ityLatency\030\037 \001(\003\022\031\n\021throttlingLatency\030  " +
      "\001(\003\022\025\n\rrequestMedLat\030! \001(\003\022\026\n\016responseMe" +
      "dLat\030\" \001(\003\022\026\n\016backendLatency\030# \001(\003\022\024\n\014ot" +
      "herLatency\030$ \001(\003\022\023\n\013gatewayType\030% \001(\t\022\r\n" +
      "\005label\030& \001(\t\022\022\n\nsubscriber\030\' \001(\t\022\032\n\022thro" +
      "ttledOutReason\030( \001(\t\022\035\n\025throttledOutTime" +
      "stamp\030) \001(\003\022\020\n\010hostname\030* \001(\t\022\021\n\terrorCo" +
      "de\030+ \001(\t\022\024\n\014errorMessage\030, \001(\t2Z\n\024Analyt" +
      "icsSendService\022B\n\rsendAnalytics\022\027.Analyt" +
      "icsStreamMessage\032\026.google.protobuf.Empty" +
      "(\001B0\n,org.wso2.micro.gateway.filter.core" +
      ".analyticsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_AnalyticsStreamMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AnalyticsStreamMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnalyticsStreamMessage_descriptor,
        new java.lang.String[] { "MessageStreamName", "MetaClientType", "ApplicationConsumerKey", "ApplicationName", "ApplicationId", "ApplicationOwner", "ApiContext", "ApiName", "ApiVersion", "ApiResourcePath", "ApiResourceTemplate", "ApiMethod", "ApiCreator", "ApiCreatorTenantDomain", "ApiTier", "ApiHostname", "Username", "UserTenantDomain", "UserIp", "UserAgent", "RequestTimestamp", "ThrottledOut", "ResponseTime", "ServiceTime", "BackendTime", "ResponseCacheHit", "ResponseSize", "Protocol", "ResponseCode", "Destination", "SecurityLatency", "ThrottlingLatency", "RequestMedLat", "ResponseMedLat", "BackendLatency", "OtherLatency", "GatewayType", "Label", "Subscriber", "ThrottledOutReason", "ThrottledOutTimestamp", "Hostname", "ErrorCode", "ErrorMessage", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
